version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
           name: Set ruby version to 2.7.0
           command: |
                rvm install 2.7.0
                echo . $(rvm 2.7.0 do rvm env --path) >> $BASH_ENV
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
